### ISSUE TITLE
Allow the client to reconnect by reloading the page

### ISSUE THREAD

**Issue by tyohan** [inlivedev/inlive-room#18]
When a browser opens a room URL, it will register a new client and join the room on registration. There will be a condition where the user might want to reload the page to rejoin because the state is not consistent. This is currently impossible because when the browser reloads, the page will register a new client instead of reusing the previous one. We will end up with a user with multiple videos from the previous one and the new one because the previous client session will need some time to fail when a user just closes the browser tab without pressing the end button.

The ideal approach should be:
1. When a client joins a room, it should have its client id on the URL or in the local persistent state like a cookie, so if the browser is reloading, the page can get that client ID if it exists and reuse it to rejoin instead of registering as a new client.
2. When the same client ID is rejoined, the previous one must be stopped before rejoining the client. This will prevent multiple videos from the same client exists in the same room.

**Comment by faiq-naufal** [comment]
I will close this issue. In current implementation, every time the client reloads the page, the client will automatically leave from the room. After reloading, the client will rejoin again with a new client session. We will not worry about a user with multiple videos from the previous one becaues the previous client session is already forced to leave the room when the client reloads the page.
