### ISSUE TITLE
404 not found after created a draft webinar event

### ISSUE THREAD

**Issue by mhaidarhanif** [inlivedev/inlive-room#238]
After created a draft webinar event:

![telegram-cloud-photo-size-5-6082253675385961860-y](https://github.com/inlivedev/inlive-room/assets/235584/a1af6440-0c31-44d7-a982-eae171142288)

Then clicked it, it shows 404 not found error:

![telegram-cloud-photo-size-5-6082253675385961861-y](https://github.com/inlivedev/inlive-room/assets/235584/4312282a-ee9d-4b00-a258-0b4a6567e7f2)

**Comment by faiq-naufal** [comment]
Hi @mhaidarhanif , thank you for reporting this issue to us. This issue happens because the title which is also used as page URL consists of emoji character. We're currently trying to fix this issue.

**Comment by GagahGK** [comment]
Hi @mhaidarhanif apologize for the inconvenience, the fix just been rolled out. currently it's still in deploying state
for now you may create the webinar without an emoji and then edit it later

**Comment by mhaidarhanif** [comment]
Thanks @faiq-naufal and @GagahGK 

I just realized that there's an emoji that could break the URL 😅

It works now 👍

**Comment by mhaidarhanif** [comment]
After published it, still with an emoji, turns out it still has 404 error.

https://room.inlive.app/webinars/peluang-karir-software-engineer-dan-web-developer---%F0%9F%90%BBbearmentor-webinar-qfgsVOgQ

<img width="485" alt="image" src="https://github.com/inlivedev/inlive-room/assets/235584/edc0f7b6-7b37-4dde-8860-fa48709f0049">

**Comment by mhaidarhanif** [comment]
Also, turns out it cannot be edited after being published. Is it possible in the next release?

I tried to cancel the event, but cannot delete it either.

**Comment by GagahGK** [comment]
> Also, turns out it cannot be edited after being published. Is it possible in the next release?
> 
> I tried to cancel the event, but cannot delete it either.

ah sorry about this one, actually you can edit it, but it looks like the menu was missing from the details page.

you can edit it by going to

https://room.inlive.app/webinars/peluang-karir-software-engineer-dan-web-developer---%F0%9F%90%BBbearmentor-webinar-qfgsVOgQ/edit

**Comment by faiq-naufal** [comment]
> I tried to cancel the event, but cannot delete it either.
@mhaidarhanif  You can only delete the event when the status is still draft. When an event is already published to public, you cannot delete that event because it may confuse people when the published event is suddenly removed. Instead of remove the event, you can cancel that event when it is no longer relevant.

**Comment by mhaidarhanif** [comment]
So basically my situation is still stuck:

- I wanted to edit, but cannot edit it.
- I decided to cancel, but cannot delete it.
- I wanted to view the details, but not possible again since it's been canceled.
- I might have to recreate the event again. Then check if a published event, not the canceled event, can be edited.

**Comment by faiq-naufal** [comment]
> But since I've canceled the event, therefore I cannot edit it again, right?
> Is it possible to at least still able to open the details?

@mhaidarhanif  Yes, you can still open the event page by clicking the more (three dots) button and copy event link. I think we should keep displaying the button to the event page when the status is canceled. Sorry for the inconvenience.

**Comment by GagahGK** [comment]
@mhaidarhanif, sorry for the inconvenience 

you should be able to view the canceled event from the three dots menu and navigate to the public page there

the 404 not found has also been fixed when trying to view the public event page on published or cancelled

thanks for the feedback, we will add an option to hide the canceled events in the list in the future

**Comment by mhaidarhanif** [comment]
@faiq-naufal 
> Yes, you can still open the event page by clicking the more (three dots) button and copy event link. I think we should keep displaying the button to the event page when the status is canceled. Sorry for the inconvenience.

Got it, it can be accessed now, I think last time it cannot be opened because of the emoji and I haven't edited it yet.

https://room.inlive.app/webinars/peluang-karir-software-engineer-dan-web-developer---%F0%9F%90%BBbearmentor-webinar-qfgsVOgQ

**Comment by mhaidarhanif** [comment]
@GagahGK 
> you should be able to view the canceled event from the three dots menu and navigate to the public page there
> the 404 not found has also been fixed when trying to view the public event page on published or cancelled

Got it, I think now it's fixed for even the canceled event.

**Comment by mhaidarhanif** [comment]
Alright I think given the last situation, since the event has been canceled. Then the best way is to recreate the event.

The 404 error not found issue has been solved.

Thanks @faiq-naufal @GagahGK

**Comment by faiq-naufal** [comment]
I will close this issue if this is solved. Thank you.
